// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snpjvyquyzavyftxnccp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNucGp2eXF1eXphdnlmdHhuY2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDg5NTMsImV4cCI6MjA2MjAyNDk1M30.StPf5pmKMLU1LckKcD4m8egtAzox8elggQ3UwXVXTc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);